"""Notification model — durable in-app alerts for users.

Notifications are the user-facing surface for the events generated by
:mod:`app.workers` — a new match appearing, a previously-uncertain
match resolving, a trial closing.

Design notes
------------
* **One row per user-visible event.**  We deliberately store one row
  per (user, event) — coordinators get one row per patient that newly
  matched, patients get one row about their own match.  This keeps
  read-state per user.
* **Loose foreign keys.**  ``patient_id`` / ``trial_id`` /
  ``match_result_id`` are nullable so we can represent system-wide
  notifications (e.g. "trial sync ran") that don't pin to a specific
  resource.
* **No HTML.**  Plain text only — rendering is the API/UI's job.  We
  carry a short ``title`` and a longer ``message`` so the inbox view
  can show titles without loading full bodies.
"""

from __future__ import annotations

import enum
import uuid

from sqlalchemy import Boolean, Column, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.database import Base


class NotificationType(str, enum.Enum):
    """Categories the API surfaces in the inbox filter dropdown."""

    NEW_MATCH = "new_match"
    MATCH_RESOLVED = "match_resolved"
    TRIAL_OPENED = "trial_opened"
    TRIAL_CLOSED = "trial_closed"
    DATA_REQUEST = "data_request"
    SYSTEM = "system"


class NotificationChannel(str, enum.Enum):
    """Where the notification was (or will be) delivered.

    We store the requested channel even for in-app-only notifications so
    that an admin auditing missed emails can tell ``IN_APP`` apart from
    ``EMAIL`` with ``delivered_at IS NULL``.
    """

    IN_APP = "in_app"
    EMAIL = "email"
    WEBHOOK = "webhook"


class Notification(Base):
    """A single user-visible notification.

    Attributes:
        user_id:         Recipient.  Required.
        notification_type: One of :class:`NotificationType`.
        channel:         How it was delivered.
        title:           Short subject line.
        message:         Full body (plain text).
        read:            Read state — toggled by the user via the API.
        delivered:       For non in-app channels, whether the dispatcher
                         has confirmed delivery.
        delivered_at:    Timestamp of confirmation (or ``None``).
        details:         Free-form JSON for the API / clients.
        patient_id:      Optional FK to the patient the event concerns.
        trial_id:        Optional FK to the trial.
        match_result_id: Optional FK to the specific match.
    """

    __tablename__ = "notifications"
    __table_args__ = (
        Index("ix_notifications_user_id", "user_id"),
        Index("ix_notifications_user_unread", "user_id", "read"),
        {"comment": "User-visible in-app notifications"},
    )

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        comment="Unique notification identifier",
    )
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        comment="Recipient user",
    )
    notification_type = Column(
        String(40),
        nullable=False,
        comment="Category enum (new_match, match_resolved, …)",
    )
    channel = Column(
        String(20),
        nullable=False,
        default=NotificationChannel.IN_APP.value,
        comment="Delivery channel (in_app, email, webhook)",
    )
    title = Column(String(255), nullable=False, comment="Short subject line")
    message = Column(Text, nullable=False, comment="Plain-text body")
    read = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="True once the user has dismissed the notification",
    )
    delivered = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="For non in-app channels, whether delivery confirmed",
    )

    # Loose links to source rows — all nullable so system notifications
    # (e.g. nightly sync ran) can omit them.
    patient_id = Column(
        UUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="SET NULL"),
        nullable=True,
    )
    trial_id = Column(
        UUID(as_uuid=True),
        ForeignKey("clinical_trials.id", ondelete="SET NULL"),
        nullable=True,
    )
    match_result_id = Column(
        UUID(as_uuid=True),
        ForeignKey("match_results.id", ondelete="SET NULL"),
        nullable=True,
    )

    details = Column(JSONB, nullable=True, comment="Arbitrary structured context")

    # ── Relationships ─────────────────────────────────────────────────
    user = relationship("User", foreign_keys=[user_id], lazy="selectin")

    def __repr__(self) -> str:  # noqa: D401
        flag = "*" if not self.read else " "
        return (
            f"<Notification{flag} {self.notification_type} "
            f"user={self.user_id} title={self.title!r}>"
        )
