"""add trial summary_cache column

Revision ID: 141f665cac92
Revises: 0f6f7433c1fd
Create Date: 2026-05-27 12:24:40.576609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '141f665cac92'
down_revision: Union[str, None] = '0f6f7433c1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_trials', sa.Column('summary_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_trials', 'summary_cache')
    # ### end Alembic commands ###
