"""drop wearable_devices and vital_readings

Revision ID: b082f10bff1e
Revises: a5dccfe2e559
Create Date: 2026-05-29 18:09:50.445834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b082f10bff1e'
down_revision: Union[str, None] = 'a5dccfe2e559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop both wearable tables.

    Alembic's autogenerate put ``wearable_devices`` first, but
    ``vital_readings`` has a FK pointing at ``wearable_devices.id`` —
    dropping the parent first violates that constraint.  Re-ordered to
    drop the child table (``vital_readings``) first, then the parent.
    """
    op.drop_index('ix_vital_readings_device_id', table_name='vital_readings')
    op.drop_index('ix_vital_readings_patient_id', table_name='vital_readings')
    op.drop_table('vital_readings')
    op.drop_index('ix_wearable_devices_patient_id', table_name='wearable_devices')
    op.drop_table('wearable_devices')


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_readings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reading_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_resting', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['wearable_devices.id'], name='vital_readings_device_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='vital_readings_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vital_readings_pkey')
    )
    op.create_index('ix_vital_readings_patient_id', 'vital_readings', ['patient_id'], unique=False)
    op.create_index('ix_vital_readings_device_id', 'vital_readings', ['device_id'], unique=False)
    op.create_table('wearable_devices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='wearable_devices_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wearable_devices_pkey')
    )
    op.create_index('ix_wearable_devices_patient_id', 'wearable_devices', ['patient_id'], unique=False)
    # ### end Alembic commands ###
