"""add llm_usage table

Revision ID: a5dccfe2e559
Revises: b4601bb48f78
Create Date: 2026-05-28 21:05:23.858663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5dccfe2e559'
down_revision: Union[str, None] = 'b4601bb48f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique usage-row identifier.'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='Provider model id (e.g. llama-3.3-70b-versatile).'),
    sa.Column('operation', sa.String(length=50), nullable=True, comment='Short tag identifying the calling service (criteria_parser / eligibility_reasoner / plain_language / …).'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='Denormalised prompt + completion tokens for fast aggregation.'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Wall-clock latency in milliseconds.'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='False if the LLM call raised; the row is still written for visibility.'),
    sa.Column('error_class', sa.String(length=120), nullable=True, comment='Exception class name when success=False.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Append-only LLM call telemetry — feeds the admin usage card.'
    )
    op.create_index('ix_llm_usage_created_at', 'llm_usage', ['created_at'], unique=False)
    op.create_index('ix_llm_usage_model', 'llm_usage', ['model'], unique=False)
    op.create_index('ix_llm_usage_operation', 'llm_usage', ['operation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_usage_operation', table_name='llm_usage')
    op.drop_index('ix_llm_usage_model', table_name='llm_usage')
    op.drop_index('ix_llm_usage_created_at', table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
