"""add notifications table

Revision ID: 588f16c0d71d
Revises: 141f665cac92
Create Date: 2026-05-27 12:38:17.875441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '588f16c0d71d'
down_revision: Union[str, None] = '141f665cac92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique notification identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Recipient user'),
    sa.Column('notification_type', sa.String(length=40), nullable=False, comment='Category enum (new_match, match_resolved, …)'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='Delivery channel (in_app, email, webhook)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short subject line'),
    sa.Column('message', sa.Text(), nullable=False, comment='Plain-text body'),
    sa.Column('read', sa.Boolean(), nullable=False, comment='True once the user has dismissed the notification'),
    sa.Column('delivered', sa.Boolean(), nullable=False, comment='For non in-app channels, whether delivery confirmed'),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('trial_id', sa.UUID(), nullable=True),
    sa.Column('match_result_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary structured context'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trial_id'], ['clinical_trials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User-visible in-app notifications'
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
