"""initial schema

Revision ID: daa879540492
Revises: 
Create Date: 2026-05-26 20:22:37.000850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daa879540492'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_trials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nct_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=30), nullable=True),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('study_type', sa.String(length=30), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interventions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sponsor', sa.String(length=500), nullable=True),
    sa.Column('enrollment_count', sa.Integer(), nullable=True),
    sa.Column('enrollment_demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('raw_eligibility_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_manually_added', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_trials_nct_id'), 'clinical_trials', ['nct_id'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('ethnicity', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fhir_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_external_id'), 'patients', ['external_id'], unique=True)
    op.create_table('medical_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('code_system', sa.String(length=30), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_events_code'), 'medical_events', ['code'], unique=False)
    op.create_index(op.f('ix_medical_events_patient_id'), 'medical_events', ['patient_id'], unique=False)
    op.create_table('trial_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=False),
    sa.Column('criterion_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('parsed_description', sa.Text(), nullable=True),
    sa.Column('temporal_constraint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_constraint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['clinical_trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_criteria_trial_id'), 'trial_criteria', ['trial_id'], unique=False)
    op.create_table('trial_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=False),
    sa.Column('facility_name', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('site_status', sa.String(length=30), nullable=False),
    sa.Column('contact_name', sa.String(length=300), nullable=True),
    sa.Column('contact_email', sa.String(length=300), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['clinical_trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_sites_trial_id'), 'trial_sites', ['trial_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Unique login e-mail address'),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False, comment='Bcrypt-hashed password'),
    sa.Column('full_name', sa.String(length=256), nullable=False, comment='User display name'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='RBAC role (patient | coordinator | clinician | admin | sponsor)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False disables login without deleting the account'),
    sa.Column('associated_patient_id', sa.UUID(), nullable=True, comment='FK to patients.id when role is PATIENT'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of most recent login'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['associated_patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Application users with RBAC roles'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wearable_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=40), nullable=False),
    sa.Column('device_name', sa.String(length=300), nullable=False),
    sa.Column('manufacturer', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wearable_devices_patient_id'), 'wearable_devices', ['patient_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique audit entry identifier'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the auditable event occurred'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='FK to users.id; NULL for system-initiated actions'),
    sa.Column('action', sa.String(length=30), nullable=False, comment='Auditable action type (see AuditAction enum)'),
    sa.Column('resource_type', sa.String(length=64), nullable=False, comment="Logical entity type, e.g. 'patient', 'trial'"),
    sa.Column('resource_id', sa.String(length=128), nullable=True, comment='Stringified ID of the affected resource'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary JSON context for the event'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='HTTP User-Agent header'),
    sa.Column('request_path', sa.String(length=2048), nullable=True, comment='HTTP request path'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP method (GET, POST, …)'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='HTTP response status code'),
    sa.Column('phi_accessed', sa.Boolean(), nullable=False, comment='True if Protected Health Information was accessed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Append-only audit log for HIPAA compliance'
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=False),
    sa.Column('patient_version', sa.Integer(), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('diversity_priority_score', sa.Float(), nullable=True),
    sa.Column('final_rank_score', sa.Float(), nullable=True),
    sa.Column('total_criteria', sa.Integer(), nullable=False),
    sa.Column('criteria_met', sa.Integer(), nullable=False),
    sa.Column('criteria_not_met', sa.Integer(), nullable=False),
    sa.Column('criteria_uncertain', sa.Integer(), nullable=False),
    sa.Column('missing_data_summary', sa.Text(), nullable=True),
    sa.Column('plain_language_summary', sa.Text(), nullable=True),
    sa.Column('summary_language', sa.String(length=10), nullable=False),
    sa.Column('coordinator_status', sa.String(length=30), nullable=False),
    sa.Column('coordinator_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.String(length=30), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trial_id'], ['clinical_trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_patient_id'), 'match_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_match_results_trial_id'), 'match_results', ['trial_id'], unique=False)
    op.create_table('patient_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_versions_patient_id'), 'patient_versions', ['patient_id'], unique=False)
    op.create_table('vital_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('reading_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('is_resting', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['wearable_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_readings_device_id'), 'vital_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_vital_readings_patient_id'), 'vital_readings', ['patient_id'], unique=False)
    op.create_table('criterion_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_result_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('evidence_event_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evaluated_by', sa.String(length=30), nullable=False),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['trial_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['medical_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criterion_evaluations_criterion_id'), 'criterion_evaluations', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_criterion_evaluations_match_result_id'), 'criterion_evaluations', ['match_result_id'], unique=False)
    op.create_table('clinician_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique feedback identifier'),
    sa.Column('match_result_id', sa.UUID(), nullable=False, comment='FK to the match result being reviewed'),
    sa.Column('criterion_evaluation_id', sa.UUID(), nullable=True, comment='FK to a specific criterion evaluation, if applicable'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK to the clinician who submitted the feedback'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='Feedback action (accepted | rejected | overridden | deferred)'),
    sa.Column('override_status', sa.String(length=20), nullable=True, comment="New criterion status if action is 'overridden' (met | not_met | uncertain)"),
    sa.Column('reason', sa.Text(), nullable=True, comment='Free-text explanation for the decision'),
    sa.Column('is_used_for_training', sa.Boolean(), nullable=False, comment='True once consumed by the fine-tuning pipeline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_evaluation_id'], ['criterion_evaluations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Clinician feedback for the learning loop'
    )
    op.create_index(op.f('ix_clinician_feedbacks_criterion_evaluation_id'), 'clinician_feedbacks', ['criterion_evaluation_id'], unique=False)
    op.create_index(op.f('ix_clinician_feedbacks_match_result_id'), 'clinician_feedbacks', ['match_result_id'], unique=False)
    op.create_index(op.f('ix_clinician_feedbacks_user_id'), 'clinician_feedbacks', ['user_id'], unique=False)
    op.create_table('uncertainty_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_result_id', sa.UUID(), nullable=False),
    sa.Column('criterion_evaluation_id', sa.UUID(), nullable=True),
    sa.Column('missing_data_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution_action', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_evaluation_id'], ['criterion_evaluations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_event_id'], ['medical_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uncertainty_flags_match_result_id'), 'uncertainty_flags', ['match_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uncertainty_flags_match_result_id'), table_name='uncertainty_flags')
    op.drop_table('uncertainty_flags')
    op.drop_index(op.f('ix_clinician_feedbacks_user_id'), table_name='clinician_feedbacks')
    op.drop_index(op.f('ix_clinician_feedbacks_match_result_id'), table_name='clinician_feedbacks')
    op.drop_index(op.f('ix_clinician_feedbacks_criterion_evaluation_id'), table_name='clinician_feedbacks')
    op.drop_table('clinician_feedbacks')
    op.drop_index(op.f('ix_criterion_evaluations_match_result_id'), table_name='criterion_evaluations')
    op.drop_index(op.f('ix_criterion_evaluations_criterion_id'), table_name='criterion_evaluations')
    op.drop_table('criterion_evaluations')
    op.drop_index(op.f('ix_vital_readings_patient_id'), table_name='vital_readings')
    op.drop_index(op.f('ix_vital_readings_device_id'), table_name='vital_readings')
    op.drop_table('vital_readings')
    op.drop_index(op.f('ix_patient_versions_patient_id'), table_name='patient_versions')
    op.drop_table('patient_versions')
    op.drop_index(op.f('ix_match_results_trial_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_patient_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_wearable_devices_patient_id'), table_name='wearable_devices')
    op.drop_table('wearable_devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trial_sites_trial_id'), table_name='trial_sites')
    op.drop_table('trial_sites')
    op.drop_index(op.f('ix_trial_criteria_trial_id'), table_name='trial_criteria')
    op.drop_table('trial_criteria')
    op.drop_index(op.f('ix_medical_events_patient_id'), table_name='medical_events')
    op.drop_index(op.f('ix_medical_events_code'), table_name='medical_events')
    op.drop_table('medical_events')
    op.drop_index(op.f('ix_patients_external_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_clinical_trials_nct_id'), table_name='clinical_trials')
    op.drop_table('clinical_trials')
    # ### end Alembic commands ###
